#! /bin/bash
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --time=00:05:00
#SBATCH --error=job.%J.err
#SBATCH --output=job.%J.out

cd $SLURM_SUBMIT_DIR

sleep 60
echo "Starting at `date`"
echo "Running on hosts: $SLURM_NODELIST"
echo "Hello"

python3 /nfs/hpcsa/python.py
